name: "Hidra Test"
description: "Run your Hidra tests directly from GitHub Actions"
author: "JoseCarlosGarcia95"
inputs:
  hidra-files:
    description: "Hidra files to run"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/hidracloud/hidra/main/install.sh)"
    - shell: bash
      run: hidra test ${{ inputs.hidra-files }}
