name: "Hidra Test"
description: "Run your Hidra tests directly from GitHub Actions"
author: "JoseCarlosGarcia95"
inputs:
  hidra-files:
    description: "Hidra files to run"
    required: true
  hidra-version:
    description: "Hidra version to use"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/hidracloud/hidra/main/install.sh) ${{ inputs.hidra-version }}"
    - shell: bash
      run: hidra test --exit-on-error ${{ inputs.hidra-files }}
